### PR TITLE
Fix reassigning of Event properties

### PR DESCRIPTION
**Pull request by ostap0207**
COB-194 Right now it's not properties, but property names

### CODE REVIEW

**Comment by willmore** [comment]
Test?

**Comment by ostap0207** [comment]
Hard to test since we don't have IE to run the tests on. Easier to test manually in this case.

**Comment by willmore** [comment]
How did you manually test this?

**Comment by ostap0207** [comment]
Gonna test manually in IE when deployed to staging.

**Comment by willmore** [comment]
That dog won't hunt...

**Comment by ostap0207** [comment]
I already checked that the piece I've changed and that is specific in IE works in browserstack by running it in browser console. But still gonna need to check as a full after deployed to staging.

**Comment by deiwin** [comment]
+1

**Comment by willmore** [comment]
> I already checked that the piece I've changed and that is specific in IE works in browserstack by running it in browser console. 

Ok - you could have mentioned that when I asked how you manually tested.

**Comment by willmore** [comment]
Are we going to upstream fixes like these?

**Comment by deiwin** [comment]
@ostap0207 has created an issue for this on the upstream project.

**Pull request merged**
